### ISSUE TITLE
bug detected

### ISSUE THREAD

**Issue by 3akare** [3akare/simple_shell#1]
unexpected result after compilation.
@mykie88
![Screenshot (64)](https://user-images.githubusercontent.com/98014597/182520060-7a710f35-6f7d-4afc-a926-b6fd159b38fd.png)

**Comment by mikenrowland** [comment]
@3akare that's a wrong usage, the first argument must indicate a path e.g /bin/ls or /bin/ls -la or /bin/pwd 
btw the shell is still not complete, some edge cases have not been resolved
